language: C
compiler:
  - gcc
before_script:
  - sh ./setup-travis.sh
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  - mkdir build
  - cd build
  - cmake ..
script:
  - make clean all test
sudo: required